{{ 
  config(
      materialized='incremental',
      unique_key='DATE_KEY',
      alias='DIM_CS_DATE'
  ) 
}}

WITH CALENDAR AS (
    SELECT
        DATEADD(DAY, SEQ4(), '2015-01-01') AS FULL_DATE
    FROM TABLE(GENERATOR(ROWCOUNT => 365*30)) -- 30 YEARS
)

SELECT
    TO_NUMBER(TO_CHAR(FULL_DATE, 'YYYYMMDD')) AS DATE_KEY,
    FULL_DATE,
    EXTRACT(DAY FROM FULL_DATE) AS DAY_OF_MONTH,
    DAYNAME(FULL_DATE) AS DAY_NAME,
    EXTRACT(DOW FROM FULL_DATE) AS DAY_OF_WEEK,
    EXTRACT(WEEK FROM FULL_DATE) AS WEEK_NUM,
    EXTRACT(MONTH FROM FULL_DATE) AS MONTH_NUM,
    MONTHNAME(FULL_DATE) AS MONTH_NAME,
    EXTRACT(QUARTER FROM FULL_DATE) AS QUARTER,
    EXTRACT(YEAR FROM FULL_DATE) AS YEAR,
    CASE WHEN DAYOFWEEK(FULL_DATE) IN (6,0) THEN TRUE ELSE FALSE END AS IS_WEEKEND
FROM CALENDAR
