# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "dbtdevlearning"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
profile: "dbtdevlearning"

model-paths: ["models"]
docs-paths: ["docs"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  database_map:
    raw:
      dev: DB_DEV_BI_RAW
      qa: DB_QA_BI_RAW
      prod: DB_P_BI_RAW

    edw:
      dev: DB_DEV_BI_EDW
      qa: DB_QA_BI_EDW
      prod: DB_P_BI_EDW
    audit_db:
      dev: DB_DEV_AUDIT
      qa: DB_UAT_AUDIT
      prod: DB_PROD_AUDIT

  raw_database: DB_DEV_BI_RAW
  edw_database: DB_DEV_BI_EDW

# on-run-start:
#   - "{{ raw_customer_sales_init_alltables() }}"
#   - "{{ edw_customer_sales_init_alltables() }}"

models:
  dbtdevlearning:
    raw:
      +database: |
        {%- if target.name == 'dev' -%} DB_DEV_BI_RAW   
        {%- elif target.name == 'qa' -%} DB_QA_BI_RAW
        {%- elif target.name == 'prod' -%} DB_P_BI_RAW
        {%- else -%} invalid_database
        {%- endif -%}
      customer_sales:
        incremental_tables:
          stg:
            +tags: ["incremental_tables", "customer_sales"]
            +schema: CS_GENERAL_STAGING
            +materialized: incremental
            +incremental_strategy: delete+insert
            +on_schema_change: ignore

        full_load_tables:
          +post-hook: "{{ log_audit() }}"
          stg:
            +schema: CS_GENERAL_STAGING
            +materialized: table
            +on_schema_change: ignore
    edw:
      customer_sales:
        +post-hook: "{{ log_audit() }}"
        incremental_tables:
          cln:
            +database: |
              {%- if target.name == 'dev' -%} DB_DEV_BI_EDW
              {%- elif target.name == 'qa' -%} DB_QA_BI_EDW
              {%- elif target.name == 'prod' -%} DB_P_BI_EDW
              {%- else -%} invalid_database
              {%- endif -%}
            +tags: ["edw", "incremental_tables", "cln", "customer_sales"]
            +schema: CS_GENERAL_CLN
            +materialized: incremental
            +incremental_strategy: delete+insert
            +on_schema_change: ignore
          dim:
            +database: |
              {%- if target.name == 'dev' -%} DB_DEV_BI_EDW
              {%- elif target.name == 'qa' -%} DB_QA_BI_EDW
              {%- elif target.name == 'prod' -%} DB_P_BI_EDW
              {%- else -%} invalid_database
              {%- endif -%}
            +tags: ["edw", "incremental_tables", "dim", "customer_sales"]
            +schema: CS_GENERAL_DIM
            +materialized: incremental
            +incremental_strategy: delete+insert
            +on_schema_change: ignore
          fact:
            +database: |
              {%- if target.name == 'dev' -%} DB_DEV_BI_EDW
              {%- elif target.name == 'qa' -%} DB_QA_BI_EDW
              {%- elif target.name == 'prod' -%} DB_P_BI_EDW
              {%- else -%} invalid_database
              {%- endif -%}
            +tags: ["edw", "incremental_tables", "fct", "customer_sales"]
            +schema: CS_GENERAL_FACT
            +materialized: incremental
            +incremental_strategy: merge
            +on_schema_change: ignore
        reporting:
          +tags: ["edw", "reporting_view", "reporting", "customer_sales"]
          +schema: CS_REPORTING_SALES
          +materialized: view
    marts:
      customer_sales:
        +database: |
          {%- if target.name == 'dev' -%} DB_DEV_BI_EDW
          {%- elif target.name == 'qa' -%} DB_QA_BI_EDW
          {%- elif target.name == 'prod' -%} DB_P_BI_EDW
          {%- else -%} invalid_database
          {%- endif -%}
        sales:
          +tags: ["edw", "reporting_view", "reporting", "customer_sales"]
          +schema: MART_SALES
          +materialized: view
seeds:
  +quote_columns: false
  +database: |
    {%- if target.name == 'dev' -%} DB_DEV_BI_RAW   
    {%- elif target.name == 'qa' -%} DB_QA_BI_RAW
    {%- elif target.name == 'prod' -%} DB_P_BI_RAW
    {%- else -%} invalid_database
    {%- endif -%}
  +schema: "SEED"
