{{
  config(
    alias='FACT_CUSTOMER_SALES',
    materialized='incremental',
    unique_key='UNIQUE_SK',
    cluster_by=['CUSTOMER_ID','PRODUCT_ID','SALES_DATE']
  )
}}

WITH S_CUSTOMER_SALES AS (
    SELECT
        CUSTOMER_SALES_KEY,
        SALES_ID,
        SALES_DATE,
        CUSTOMER_ID,
        PRODUCT_ID,
        QUANTITY,
        UNIT_PRICE,
        PROMOTION_ID,
        DISCOUNT,
        NET_PRICE,
        TOTAL_REVENUE,
        CREATED_AT,
        UPDATED_AT
    FROM {{ ref('edw_cs_cln_customer_sales') }}
)

SELECT
    {{dbt_utils.generate_surrogate_key(['CS.SALES_ID', 'CS.CUSTOMER_ID', 'CS.PRODUCT_ID', 'CS.SALES_DATE', 'CS.UPDATED_AT'])}} AS UNIQUE_SK,
    CS.CUSTOMER_SALES_KEY,
    CS.SALES_ID,
    CS.SALES_DATE,
    CUST.CUSTOMER_KEY,
    CS.CUSTOMER_ID,
    CUST.CUSTOMER_NAME,
    REG.REGION_NAME,
    REG.COUNTRY,
    CS.PRODUCT_ID,
    PROD.PRODUCT_NAME,
    CS.QUANTITY,
    CS.UNIT_PRICE,
    CS.PROMOTION_ID,
    PROMO.PROMOTION_NAME,
    PROMO.START_DATE AS PROMOTION_START_DATE,
    PROMO.END_DATE AS PROMOTION_END_DATE,
    PROMO.DISCOUNT_PERCENT AS PROMOTION_DISCOUNT,    
    CS.DISCOUNT,
    CS.NET_PRICE,
    CS.TOTAL_REVENUE,
    CS.CREATED_AT,
    CS.UPDATED_AT,
    DATE.DATE_KEY AS SALES_DATE_KEY,
    DATE.DAY_OF_MONTH AS SALES_DAY_OF_MONTH,
    DATE.DAY_NAME AS SALES_DAY_NAME,
    DATE.DAY_OF_WEEK AS SALES_DAY_OF_WEEK,
    DATE.WEEK_NUM AS SALES_WEEK_NUM,
    DATE.MONTH_NUM AS SALES_MONTH_NUM,
    DATE.MONTH_NAME AS SALES_MONTH_NAME,
    DATE.QUARTER AS SALES_QUARTER,
    DATE.YEAR AS SALES_YEAR,
    DATE.IS_WEEKEND AS SALES_IS_WEEKEND
FROM S_CUSTOMER_SALES AS CS
LEFT JOIN {{ref ('edw_cs_dim_customers')}} AS CUST
    ON CS.CUSTOMER_ID = CUST.CUSTOMER_ID
    AND CUST.IS_ACTIVE = TRUE
LEFT JOIN {{ref ('edw_cs_dim_products')}} AS PROD
    ON CS.PRODUCT_ID = PROD.PRODUCT_ID
    AND PROD.IS_ACTIVE = TRUE
LEFT  JOIN {{ref('edw_cs_dim_promotions') }} AS PROMO
    ON CS.PROMOTION_ID = PROMO.PROMOTION_ID
LEFT JOIN {{ref ('edw_cs_dim_region')}} AS REG
    ON CUST.REGION_ID = REG.REGION_ID
LEFT JOIN {{ref ('edw_cs_dim_cs_date')}} AS DATE
    ON CS.SALES_DATE = to_char(DATE.FULL_DATE, 'YYYY-MM-DD')
