{{
    config(
        alias='FACT_CUSTOMER_SALES',
        unique_key='UNIQUE_KEY'
    )
}}

WITH BAS_CUSTOMER AS (
    SELECT        
        CUSTOMER_ID,
        CUSTOMER_NAME        
    FROM {{ source('CUSTOMER_SALES_SOURCE', 'BAS_CUSTOMERS') }}
),
BAS_PRODUCTS AS (
    SELECT        
        PRODUCT_ID,
        PRODUCT_NAME
    FROM {{ source('CUSTOMER_SALES_SOURCE', 'BAS_PRODUCTS') }}
),
BAS_PROMOTIONS AS (
    SELECT        
        PROMOTION_ID,
        PROMOTION_NAME
    FROM {{ source('CUSTOMER_SALES_SOURCE', 'BAS_PROMOTIONS') }}
),
BAS_SALES AS (
    SELECT        
        *
    FROM {{ source('CUSTOMER_SALES_SOURCE', 'BAS_CUSTOMER_SALES') }}
),

FACT_CUSTOMER_SALES AS (
    SELECT
        CONCAT_WS('-',BS.CUSTOMER_ID, BS.SALES_ID, BS.PRODUCT_ID, TO_CHAR(TO_DATE(BS.SALES_DATE), 'YYYYMMDD')) AS UNIQUE_KEY,
        BS.SALES_ID,
        BS.SALES_DATE,
        BS.CUSTOMER_ID,
        BC.CUSTOMER_NAME,
        BS.PRODUCT_ID,
        BP.PRODUCT_NAME,
        BS.QUANTITY,
        BS.UNIT_PRICE,
        BPM.PROMOTION_ID,
        BPM.PROMOTION_NAME,
        BS.DISCOUNT,
        BS.NET_PRICE,
        BS.TOTAL_REVENUE,
        CURRENT_TIMESTAMP() AS CREATED_AT,
        CURRENT_TIMESTAMP() AS UPDATED_AT
    FROM BAS_SALES BS
    INNER JOIN BAS_CUSTOMER BC ON BS.CUSTOMER_ID = BC.CUSTOMER_ID
    INNER JOIN BAS_PRODUCTS BP ON BS.PRODUCT_ID = BP.PRODUCT_ID    
    INNER JOIN BAS_PROMOTIONS BPM ON BS.PROMOTION_ID = BPM.PROMOTION_ID
)

SELECT *
FROM FACT_CUSTOMER_SALES

