name: Build & Deploy dbt Docs

on:
  push:
    branches: [ main ]

jobs:
  dbt-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dbt
        run: pip install dbt-core dbt-snowflake  # change adapter if needed

      # Create profiles.yml dynamically from secrets
      - name: Configure dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOL
          dbtdevlearning:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: SDSHEAP-TB75689
                user: raju555
                password: AdvaitSoni@123!
                role: ACCOUNTADMIN
                warehouse: COMPUTE_WH
                database: DB_DEV_BI_RAW
                schema: GENERAL
          EOL

      - name: Build dbt docs
        run: |
          dbt deps
          dbt docs generate --target dev

      
